/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DepartamentoDAO;
import DAO.SexoDAO;
import DAO.TrabajadorDAO;
import DTO.DepartamentoDTO;
import DTO.SexoDTO;
import DTO.TrabajadorDTO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vasal
 */
public class Vista extends javax.swing.JFrame {
    TrabajadorDAO trDAO= new TrabajadorDAO();
    SexoDAO sxDAO = new SexoDAO();
    DepartamentoDAO dptoDAO = new DepartamentoDAO();
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        llenaDepartamentos();
        llenaSexo();
        llenaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreEmpresa = new javax.swing.JLabel();
        jpListaEmpleados = new javax.swing.JPanel();
        lbListaEmpleados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaEmpleados = new javax.swing.JTable();
        jlbSelecDepto = new javax.swing.JLabel();
        jcbDepartamentos = new javax.swing.JComboBox<>();
        jpNuevoEmpleado = new javax.swing.JPanel();
        jlbNuevoEmpleado = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlbApellidoM = new javax.swing.JLabel();
        jtfApellidoM = new javax.swing.JTextField();
        jlbRUT = new javax.swing.JLabel();
        jtfRUT = new javax.swing.JTextField();
        jlbSexo = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jlbApellidoP = new javax.swing.JLabel();
        jtfApellidoP = new javax.swing.JTextField();
        jlbEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jlbAnyoIngreso = new javax.swing.JLabel();
        jllbDpto = new javax.swing.JLabel();
        jcbDpto = new javax.swing.JComboBox<>();
        jsAnioIngreso = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nombreEmpresa.setText("XYZ");

        jpListaEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbListaEmpleados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbListaEmpleados.setText("Lista Empleados");

        jtListaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RUT", "Nombre Completo", "Email", "Sexo", "Año ingreso", "Departamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaEmpleados);

        jlbSelecDepto.setText("Departamento:");

        jcbDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpListaEmpleadosLayout = new javax.swing.GroupLayout(jpListaEmpleados);
        jpListaEmpleados.setLayout(jpListaEmpleadosLayout);
        jpListaEmpleadosLayout.setHorizontalGroup(
            jpListaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaEmpleadosLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(lbListaEmpleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpListaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListaEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbSelecDepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpListaEmpleadosLayout.setVerticalGroup(
            jpListaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbListaEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpListaEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSelecDepto)
                    .addComponent(jcbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpNuevoEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbNuevoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNuevoEmpleado.setText("Nuevo Empleado");

        jlbNombre.setText("Nombre");

        jlbApellidoM.setText("Apellido Materno");

        jlbRUT.setText("RUT");

        jlbSexo.setText("Sexo");

        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jlbApellidoP.setText("Apellido Paterno");

        jlbEmail.setText("Email");

        jlbAnyoIngreso.setText("Año ingreso");

        jllbDpto.setText("Departamento");

        jcbDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jsAnioIngreso.setValue(2021);

        javax.swing.GroupLayout jpNuevoEmpleadoLayout = new javax.swing.GroupLayout(jpNuevoEmpleado);
        jpNuevoEmpleado.setLayout(jpNuevoEmpleadoLayout);
        jpNuevoEmpleadoLayout.setHorizontalGroup(
            jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                        .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfApellidoM)
                            .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                                        .addComponent(jlbRUT)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtfRUT))
                                .addGap(18, 18, 18)
                                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbSexo)))
                            .addComponent(jtfNombre)
                            .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbApellidoM)
                                    .addComponent(jlbNombre)
                                    .addComponent(jlbNuevoEmpleado))
                                .addGap(0, 213, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail)
                            .addComponent(jtfApellidoP)
                            .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbApellidoP)
                                    .addComponent(jlbEmail)
                                    .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jsAnioIngreso, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbAnyoIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(47, 47, 47)
                                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                                        .addComponent(jllbDpto)
                                        .addGap(0, 175, Short.MAX_VALUE))
                                    .addComponent(jcbDpto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jpNuevoEmpleadoLayout.setVerticalGroup(
            jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbNuevoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(jlbApellidoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbApellidoM)
                    .addComponent(jlbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbRUT)
                    .addComponent(jlbSexo)
                    .addComponent(jlbAnyoIngreso)
                    .addComponent(jllbDpto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsAnioIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(nombreEmpresa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpListaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpListaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jpNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        TrabajadorDTO trabajador = new TrabajadorDTO();
        
        trabajador.setId(trDAO.cantidadTrabajadores() + 1);
        trabajador.setNombre(jtfNombre.getText());
        trabajador.setApellido_paterno(jtfApellidoP.getText());
        trabajador.setApellido_materno(jtfApellidoM.getText());
        trabajador.setEmail(jtfEmail.getText());
        trabajador.setRut(jtfRUT.getText());
        trabajador.setSexo_id(sxDAO.buscaId(jcbSexo.getSelectedItem().toString()));
        trabajador.setAnio_ingreso((int)jsAnioIngreso.getValue());
        trabajador.setDepartamento_id(dptoDAO.buscaId(jcbDpto.getSelectedItem().toString()));
        
        trDAO.Agregar(trabajador);
        llenaTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    
    public void llenaTabla(){
        DefaultTableModel model = (DefaultTableModel) jtListaEmpleados.getModel();
        model.setRowCount(0);
        for(TrabajadorDTO trab : trDAO.buscarTodos()){
            Object[] row = {trab.getRut(), trab.getNombre()+" "+trab.getApellido_paterno()+" "+trab.getApellido_materno(), trab.getEmail(), sxDAO.buscaDesc(trab.getSexo_id()), trab.getAnio_ingreso(),dptoDAO.buscaNombre(trab.getDepartamento_id())};
            model.addRow(row);
        }
    }
    
    public void llenaSexo(){
        jcbSexo.removeAllItems();
        jcbSexo.addItem("Elija");
        for(SexoDTO sexDTO : sxDAO.buscarTodos()){
            jcbSexo.addItem(sexDTO.getDescripcion());
        }
    }
    
    public void llenaDepartamentos(){
        jcbDepartamentos.removeAllItems();
        jcbDpto.removeAllItems();
        jcbDepartamentos.addItem("Elija");
        jcbDpto.addItem("Elija");
        for(DepartamentoDTO dep : dptoDAO.buscarTodos()){
            jcbDepartamentos.addItem(dep.getNombre());
            jcbDpto.addItem(dep.getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbDepartamentos;
    private javax.swing.JComboBox<String> jcbDpto;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JLabel jlbAnyoIngreso;
    private javax.swing.JLabel jlbApellidoM;
    private javax.swing.JLabel jlbApellidoP;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbNuevoEmpleado;
    private javax.swing.JLabel jlbRUT;
    private javax.swing.JLabel jlbSelecDepto;
    private javax.swing.JLabel jlbSexo;
    private javax.swing.JLabel jllbDpto;
    private javax.swing.JPanel jpListaEmpleados;
    private javax.swing.JPanel jpNuevoEmpleado;
    private javax.swing.JSpinner jsAnioIngreso;
    private javax.swing.JTable jtListaEmpleados;
    private javax.swing.JTextField jtfApellidoM;
    private javax.swing.JTextField jtfApellidoP;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfRUT;
    private javax.swing.JLabel lbListaEmpleados;
    private javax.swing.JLabel nombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
